namespace Finance.Nomenclature.API.Seeding;

/// <summary>
/// The bundled static ISO 4217 currency list (~180 active currencies) used by the startup seeder
/// (SDD-NOM-001 §2.5). The seeder upserts these rows WITHOUT overwriting existing currencies and never
/// removes a currency, because historical documents reference currencies by their ISO code.
/// </summary>
public static class Iso4217CurrencyList
{
    /// <summary>The bundled ISO 4217 currencies seeded on first startup when seeding is enabled.</summary>
    public static IReadOnlyList<Iso4217Currency> All { get; } =
    [
        new("AED", "United Arab Emirates Dirham", "د.إ"),
        new("AFN", "Afghan Afghani", "؋"),
        new("ALL", "Albanian Lek", "L"),
        new("AMD", "Armenian Dram", "֏"),
        new("ANG", "Netherlands Antillean Guilder", "ƒ"),
        new("AOA", "Angolan Kwanza", "Kz"),
        new("ARS", "Argentine Peso", "$"),
        new("AUD", "Australian Dollar", "$"),
        new("AWG", "Aruban Florin", "ƒ"),
        new("AZN", "Azerbaijani Manat", "₼"),
        new("BAM", "Bosnia-Herzegovina Convertible Mark", "KM"),
        new("BBD", "Barbadian Dollar", "$"),
        new("BDT", "Bangladeshi Taka", "৳"),
        new("BGN", "Bulgarian Lev", "лв"),
        new("BHD", "Bahraini Dinar", ".د.ب"),
        new("BIF", "Burundian Franc", "FBu"),
        new("BMD", "Bermudan Dollar", "$"),
        new("BND", "Brunei Dollar", "$"),
        new("BOB", "Bolivian Boliviano", "Bs."),
        new("BRL", "Brazilian Real", "R$"),
        new("BSD", "Bahamian Dollar", "$"),
        new("BTN", "Bhutanese Ngultrum", "Nu."),
        new("BWP", "Botswanan Pula", "P"),
        new("BYN", "Belarusian Ruble", "Br"),
        new("BZD", "Belize Dollar", "$"),
        new("CAD", "Canadian Dollar", "$"),
        new("CDF", "Congolese Franc", "FC"),
        new("CHF", "Swiss Franc", "CHF"),
        new("CLP", "Chilean Peso", "$"),
        new("CNY", "Chinese Yuan", "¥"),
        new("COP", "Colombian Peso", "$"),
        new("CRC", "Costa Rican Colón", "₡"),
        new("CUP", "Cuban Peso", "$"),
        new("CVE", "Cape Verdean Escudo", "$"),
        new("CZK", "Czech Koruna", "Kč"),
        new("DJF", "Djiboutian Franc", "Fdj"),
        new("DKK", "Danish Krone", "kr"),
        new("DOP", "Dominican Peso", "$"),
        new("DZD", "Algerian Dinar", "دج"),
        new("EGP", "Egyptian Pound", "£"),
        new("ERN", "Eritrean Nakfa", "Nfk"),
        new("ETB", "Ethiopian Birr", "Br"),
        new("EUR", "Euro", "€"),
        new("FJD", "Fijian Dollar", "$"),
        new("FKP", "Falkland Islands Pound", "£"),
        new("GBP", "British Pound Sterling", "£"),
        new("GEL", "Georgian Lari", "₾"),
        new("GHS", "Ghanaian Cedi", "₵"),
        new("GIP", "Gibraltar Pound", "£"),
        new("GMD", "Gambian Dalasi", "D"),
        new("GNF", "Guinean Franc", "FG"),
        new("GTQ", "Guatemalan Quetzal", "Q"),
        new("GYD", "Guyanaese Dollar", "$"),
        new("HKD", "Hong Kong Dollar", "$"),
        new("HNL", "Honduran Lempira", "L"),
        new("HRK", "Croatian Kuna", "kn"),
        new("HTG", "Haitian Gourde", "G"),
        new("HUF", "Hungarian Forint", "Ft"),
        new("IDR", "Indonesian Rupiah", "Rp"),
        new("ILS", "Israeli New Shekel", "₪"),
        new("INR", "Indian Rupee", "₹"),
        new("IQD", "Iraqi Dinar", "ع.د"),
        new("IRR", "Iranian Rial", "﷼"),
        new("ISK", "Icelandic Króna", "kr"),
        new("JMD", "Jamaican Dollar", "$"),
        new("JOD", "Jordanian Dinar", "د.ا"),
        new("JPY", "Japanese Yen", "¥"),
        new("KES", "Kenyan Shilling", "Sh"),
        new("KGS", "Kyrgystani Som", "с"),
        new("KHR", "Cambodian Riel", "៛"),
        new("KMF", "Comorian Franc", "CF"),
        new("KPW", "North Korean Won", "₩"),
        new("KRW", "South Korean Won", "₩"),
        new("KWD", "Kuwaiti Dinar", "د.ك"),
        new("KYD", "Cayman Islands Dollar", "$"),
        new("KZT", "Kazakhstani Tenge", "₸"),
        new("LAK", "Laotian Kip", "₭"),
        new("LBP", "Lebanese Pound", "ل.ل"),
        new("LKR", "Sri Lankan Rupee", "Rs"),
        new("LRD", "Liberian Dollar", "$"),
        new("LSL", "Lesotho Loti", "L"),
        new("LYD", "Libyan Dinar", "ل.د"),
        new("MAD", "Moroccan Dirham", "د.م."),
        new("MDL", "Moldovan Leu", "L"),
        new("MGA", "Malagasy Ariary", "Ar"),
        new("MKD", "Macedonian Denar", "ден"),
        new("MMK", "Myanmar Kyat", "K"),
        new("MNT", "Mongolian Tugrik", "₮"),
        new("MOP", "Macanese Pataca", "P"),
        new("MRU", "Mauritanian Ouguiya", "UM"),
        new("MUR", "Mauritian Rupee", "Rs"),
        new("MVR", "Maldivian Rufiyaa", ".ރ"),
        new("MWK", "Malawian Kwacha", "MK"),
        new("MXN", "Mexican Peso", "$"),
        new("MYR", "Malaysian Ringgit", "RM"),
        new("MZN", "Mozambican Metical", "MT"),
        new("NAD", "Namibian Dollar", "$"),
        new("NGN", "Nigerian Naira", "₦"),
        new("NIO", "Nicaraguan Córdoba", "C$"),
        new("NOK", "Norwegian Krone", "kr"),
        new("NPR", "Nepalese Rupee", "Rs"),
        new("NZD", "New Zealand Dollar", "$"),
        new("OMR", "Omani Rial", "ر.ع."),
        new("PAB", "Panamanian Balboa", "B/."),
        new("PEN", "Peruvian Sol", "S/"),
        new("PGK", "Papua New Guinean Kina", "K"),
        new("PHP", "Philippine Peso", "₱"),
        new("PKR", "Pakistani Rupee", "Rs"),
        new("PLN", "Polish Zloty", "zł"),
        new("PYG", "Paraguayan Guarani", "₲"),
        new("QAR", "Qatari Rial", "ر.ق"),
        new("RON", "Romanian Leu", "lei"),
        new("RSD", "Serbian Dinar", "дин."),
        new("RUB", "Russian Ruble", "₽"),
        new("RWF", "Rwandan Franc", "FRw"),
        new("SAR", "Saudi Riyal", "ر.س"),
        new("SBD", "Solomon Islands Dollar", "$"),
        new("SCR", "Seychellois Rupee", "Rs"),
        new("SDG", "Sudanese Pound", "ج.س."),
        new("SEK", "Swedish Krona", "kr"),
        new("SGD", "Singapore Dollar", "$"),
        new("SHP", "Saint Helena Pound", "£"),
        new("SLE", "Sierra Leonean Leone", "Le"),
        new("SOS", "Somali Shilling", "Sh"),
        new("SRD", "Surinamese Dollar", "$"),
        new("SSP", "South Sudanese Pound", "£"),
        new("STN", "São Tomé and Príncipe Dobra", "Db"),
        new("SVC", "Salvadoran Colón", "$"),
        new("SYP", "Syrian Pound", "£"),
        new("SZL", "Swazi Lilangeni", "L"),
        new("THB", "Thai Baht", "฿"),
        new("TJS", "Tajikistani Somoni", "ЅМ"),
        new("TMT", "Turkmenistani Manat", "m"),
        new("TND", "Tunisian Dinar", "د.ت"),
        new("TOP", "Tongan Paʻanga", "T$"),
        new("TRY", "Turkish Lira", "₺"),
        new("TTD", "Trinidad and Tobago Dollar", "$"),
        new("TWD", "New Taiwan Dollar", "$"),
        new("TZS", "Tanzanian Shilling", "Sh"),
        new("UAH", "Ukrainian Hryvnia", "₴"),
        new("UGX", "Ugandan Shilling", "Sh"),
        new("USD", "United States Dollar", "$"),
        new("UYU", "Uruguayan Peso", "$"),
        new("UZS", "Uzbekistani Som", "сўм"),
        new("VED", "Venezuelan Bolívar Digital", "Bs."),
        new("VES", "Venezuelan Bolívar Soberano", "Bs."),
        new("VND", "Vietnamese Dong", "₫"),
        new("VUV", "Vanuatu Vatu", "VT"),
        new("WST", "Samoan Tala", "T"),
        new("XAF", "Central African CFA Franc", "FCFA"),
        new("XCD", "East Caribbean Dollar", "$"),
        new("XOF", "West African CFA Franc", "CFA"),
        new("XPF", "CFP Franc", "₣"),
        new("YER", "Yemeni Rial", "﷼"),
        new("ZAR", "South African Rand", "R"),
        new("ZMW", "Zambian Kwacha", "ZK"),
        new("ZWL", "Zimbabwean Dollar", "$")
    ];
}
